services:
  vscode-server:
    container_name: my-code-server
    image: ghcr.io/nerasse/my-code-server:main
    ports:
      - "8585:8586"
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
    environment:
      - PORT=8586
      - TOKEN=${CODE_SERVER_TOKEN}
    volumes:
     - vscode-data:/home/vscodeuser/
    
    #optional : add the network
    networks:
      - vscode-server-network

volumes:
  vscode-data:

#optional : add the network 
networks:
  vscode-server-network:
    external: false
    name: vscode-server-network